#!/bin/bash
set -e -x
setenforce 0
yum update -y
yum group install "Development Tools" -y
yum install wget -y
wget http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-7.noarch.rpm
rpm -ivh epel-release-7-7.noarch.rpm
yum install mlocate wget gcc openssl-* openssh* -y
yum install httpd -y 
rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
yum install php70w -y
yum install http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm -y
yum list | grep percona
yum install Percona-Server-server-57 -y
sleep 2
service httpd start
